var annotated_dup =
[
    [ "AirfoilCoefficients", "struct_airfoil_coefficients.html", "struct_airfoil_coefficients" ],
    [ "AirfoilOptimizer", "class_airfoil_optimizer.html", "class_airfoil_optimizer" ],
    [ "AviationProfileParameters", "struct_aviation_profile_parameters.html", "struct_aviation_profile_parameters" ],
    [ "BinaryAirfoilCoefficients", "struct_binary_airfoil_coefficients.html", "struct_binary_airfoil_coefficients" ],
    [ "Component", "struct_component.html", "struct_component" ],
    [ "Config", "class_config.html", [
      [ "ApplicationParams", "struct_config_1_1_application_params.html", null ],
      [ "OptimizerParams", "struct_config_1_1_optimizer_params.html", "struct_config_1_1_optimizer_params" ],
      [ "SimulationParams", "struct_config_1_1_simulation_params.html", "struct_config_1_1_simulation_params" ]
    ] ],
    [ "ConfigurationReader", "class_configuration_reader.html", "class_configuration_reader" ],
    [ "DudOptimizer", "class_dud_optimizer.html", "class_dud_optimizer" ],
    [ "DudScrambler", "class_dud_scrambler.html", "class_dud_scrambler" ],
    [ "ExceptionHandler", "struct_exception_handler.html", "struct_exception_handler" ],
    [ "FitnessModel", "class_fitness_model.html", "class_fitness_model" ],
    [ "GeneticOptimizer", "class_genetic_optimizer.html", "class_genetic_optimizer" ],
    [ "Genome", "class_genome.html", "class_genome" ],
    [ "GenomeScrambler", "class_genome_scrambler.html", "class_genome_scrambler" ],
    [ "Geometry", "class_geometry.html", "class_geometry" ],
    [ "LogWriter", "class_log_writer.html", "class_log_writer" ],
    [ "MainWindowObjects", "struct_main_window_objects.html", "struct_main_window_objects" ],
    [ "Model", "class_model.html", "class_model" ],
    [ "Plot", "struct_plot.html", "struct_plot" ],
    [ "PlotDialog", "class_plot_dialog.html", "class_plot_dialog" ],
    [ "Point", "class_point.html", "class_point" ],
    [ "QSimulationProxy", "class_q_simulation_proxy.html", "class_q_simulation_proxy" ],
    [ "SchedulerWorker", "class_scheduler_worker.html", "class_scheduler_worker" ],
    [ "SettingsDialog", "class_settings_dialog.html", "class_settings_dialog" ],
    [ "SettingsObjects", "struct_settings_objects.html", "struct_settings_objects" ],
    [ "SimResults", "class_sim_results.html", "class_sim_results" ],
    [ "SimulationHandler", "class_simulation_handler.html", "class_simulation_handler" ],
    [ "SimulationProxy", "class_simulation_proxy.html", "class_simulation_proxy" ],
    [ "SimulationScheduler", "class_simulation_scheduler.html", "class_simulation_scheduler" ],
    [ "SingleCrossoverMultiMutationScrambler", "class_single_crossover_multi_mutation_scrambler.html", "class_single_crossover_multi_mutation_scrambler" ],
    [ "Task", "struct_task.html", "struct_task" ],
    [ "TimeManager", "class_time_manager.html", "class_time_manager" ],
    [ "TiXmlAttribute", "class_ti_xml_attribute.html", "class_ti_xml_attribute" ],
    [ "TiXmlAttributeSet", "class_ti_xml_attribute_set.html", "class_ti_xml_attribute_set" ],
    [ "TiXmlBase", "class_ti_xml_base.html", "class_ti_xml_base" ],
    [ "TiXmlComment", "class_ti_xml_comment.html", "class_ti_xml_comment" ],
    [ "TiXmlCursor", "struct_ti_xml_cursor.html", "struct_ti_xml_cursor" ],
    [ "TiXmlDeclaration", "class_ti_xml_declaration.html", "class_ti_xml_declaration" ],
    [ "TiXmlDocument", "class_ti_xml_document.html", "class_ti_xml_document" ],
    [ "TiXmlElement", "class_ti_xml_element.html", "class_ti_xml_element" ],
    [ "TiXmlHandle", "class_ti_xml_handle.html", "class_ti_xml_handle" ],
    [ "TiXmlNode", "class_ti_xml_node.html", "class_ti_xml_node" ],
    [ "TiXmlOutStream", "class_ti_xml_out_stream.html", "class_ti_xml_out_stream" ],
    [ "TiXmlParsingData", "class_ti_xml_parsing_data.html", "class_ti_xml_parsing_data" ],
    [ "TiXmlPrinter", "class_ti_xml_printer.html", "class_ti_xml_printer" ],
    [ "TiXmlString", "class_ti_xml_string.html", "class_ti_xml_string" ],
    [ "TiXmlText", "class_ti_xml_text.html", "class_ti_xml_text" ],
    [ "TiXmlUnknown", "class_ti_xml_unknown.html", "class_ti_xml_unknown" ],
    [ "TiXmlVisitor", "class_ti_xml_visitor.html", "class_ti_xml_visitor" ],
    [ "View", "class_view.html", "class_view" ]
];